//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteProgramador
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public int id_rule { get; set; }
        public string name { get; set; }
        public decimal salary { get; set; }
        public string gender { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public byte[] modified_at { get; set; }
    
        public virtual rule rule { get; set; }
    }
}
