//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteProgramador
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule
    {
        public rule()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public byte[] modifield_at { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
    }
}
